### ISSUE TITLE
plz upgrade

### ISSUE THREAD

**Issue by elsieyin** [neptune-ai/neptune-contrib#105]
i'm trying on my pycharm with conda envs, this [lightGBM case on neptune.ai](https://docs.neptune.ai/integrations/lightgbm.html), it throw a series of errors,
great software, plz upgrade
```python
F:\Anaconda\envs\kaggle\python.exe "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\pydevconsole.py" --mode=client --port=3967
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['F:\\iPynb\\LendingClub', 'F:/iPynb/LendingClub'])
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.18.1
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] on win32
In[2]: runfile('F:/iPynb/LendingClub/main.py', wdir='F:/iPynb/LendingClub')
Traceback (most recent call last):
  File "F:\Anaconda\envs\kaggle\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-512b071ef48b>", line 1, in <module>
    runfile('F:/iPynb/LendingClub/main.py', wdir='F:/iPynb/LendingClub')
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/iPynb/LendingClub/main.py", line 14, in <module>
    from scikitplot.metrics import plot_roc, plot_confusion_matrix, plot_precision_recall
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scikitplot\__init__.py", line 2, in <module>
    from . import metrics, cluster, decomposition, estimators
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scikitplot\metrics.py", line 14, in <module>
    from sklearn.metrics import confusion_matrix
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from .base import clone
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\sklearn\base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\sklearn\utils\__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\sklearn\utils\class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\sklearn\utils\validation.py", line 25, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\sklearn\utils\fixes.py", line 18, in <module>
    import scipy.stats
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scipy\stats\__init__.py", line 388, in <module>
    from .stats import *
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scipy\stats\stats.py", line 174, in <module>
    from scipy.spatial.distance import cdist
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scipy\spatial\__init__.py", line 102, in <module>
    from ._geometric_slerp import geometric_slerp
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scipy\spatial\_geometric_slerp.py", line 8, in <module>
    from scipy.spatial.distance import euclidean
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scipy\spatial\distance.py", line 121, in <module>
    from ..special import rel_entr
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scipy\special\__init__.py", line 645, in <module>
    from ._ellip_harm import (
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\scipy\special\_ellip_harm.py", line 4, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "_ellip_harm_2.pyx", line 9, in init scipy.special._ellip_harm_2
ModuleNotFoundError: No module named 'scipy._lib._ccallback'```

**Comment by PiotrJander** [comment]
Hi @elsieyin , I cannot see any Neptune-related files in your stack trace, so perhaps your problem isn't specific to Neptune.

Have you tried running lightGBM without Neptune? Does it work this way?

If you do think this is a problem with Neptune, could you provide a minimal list of conda dependencies and a script which reproduces this problem?

**Comment by elsieyin** [comment]
i don't know i have both conda and pip . i don't even know which dependency it is using Iam confused.
do you support Python3.7? it seems this morning,
I uninstalled scipy1.5 and installed scipy1.4.1 solved this problem

**Comment by elsieyin** [comment]
i don't know, i am using conda install, but sometimes pip install .
I checked its so very strange and confusing. I remember I pip uninstalled scipy1.5 and pip install scipy==1.4.1 this morning.
but in conda env for this project. when I now typed pip list ,it shows scipy ==1.5, it seems it has a cache or sth?
```(kaggle) F:\iPynb>pip uninstall scipy
Found existing installation: scipy 1.5.2
Uninstalling scipy-1.5.2:```

```(kaggle) F:\iPynb>pip install scipy==1.4.1
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting scipy==1.4.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/61/51/046cbc61c7607e5ecead6ff1a9453fba5e7e47a5ea8d608cc7036586a5ef/scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
Requirement already satisfied: numpy>=1.13.3 in c:\users\86182\appdata\roaming\python\python37\site-packages (from scipy==1.4.1) (1.18.5)
Installing collected packages: scipy
Successfully installed scipy-1.4.1
```
I don't know...
but conda list show now scipy==1.4.1

**Comment by elsieyin** [comment]
besides I don't know why it can't accept categorical type.
```Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.18.1
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] on win32
runfile('F:/iPynb/LendingClub/train.py', wdir='F:/iPynb/LendingClub')
https://ui.neptune.ai/ria230/LendingClub/e/LEN-1
Traceback (most recent call last):
  File "F:\Anaconda\envs\kaggle\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8cbdee32f5a9>", line 1, in <module>
    runfile('F:/iPynb/LendingClub/train.py', wdir='F:/iPynb/LendingClub')
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/iPynb/LendingClub/train.py", line 54, in <module>
    callbacks=[neptune_monitor()],  # monitor learning curves
  File "F:\Anaconda\envs\kaggle\lib\site-packages\lightgbm\engine.py", line 228, in train
    booster = Booster(params=params, train_set=train_set)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\lightgbm\basic.py", line 1664, in __init__
    train_set.construct().handle,
  File "F:\Anaconda\envs\kaggle\lib\site-packages\lightgbm\basic.py", line 1037, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\lightgbm\basic.py", line 782, in _lazy_init
    self.pandas_categorical)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\lightgbm\basic.py", line 295, in _data_from_pandas
    + ', '.join(data.columns[bad_indices]))
ValueError: DataFrame.dtypes for data must be int, float or bool.
Did not expect the data types in the following fields: grade, subGrade
```
which seems to work fine on my local environment. 
New pandas support datetype `Categorical` which seem to go wrong in many cases,
[https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics-dtypes](url)
 I can change code for this to run ofcourse.

**Comment by PiotrJander** [comment]
Hi @elsieyin , good to hear that changing your SciPy version helped.

As for your second problem, judging by the stack trace, it doesn't seem like your problem is related to Neptune - unless I am mistaken, then please provide more information.

If you can bypass the problem for now by changing you code, great.

**Comment by elsieyin** [comment]
thank you
